# Generated by Django 2.1.3 on 2019-06-20 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('module', '0003_auto_20190620_1038'),
        ('apitest', '0002_userinfo_createtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApicaseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apicase_name', models.CharField(max_length=50, verbose_name='用例名称')),
                ('apicase_desc', models.CharField(max_length=100, null=True, verbose_name='用例描述')),
                ('apicase_url', models.CharField(max_length=100, verbose_name='请求地址')),
                ('apicase_method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('patch', 'patch'), ('delete', 'delete')], default='get', max_length=20, verbose_name='请求方式')),
                ('apicase_head', models.CharField(max_length=100, null=True, verbose_name='请求头信息')),
                ('apicase_param', models.CharField(max_length=200, null=True, verbose_name='请求参数')),
                ('apicase_relydata', models.CharField(max_length=100, null=True, verbose_name='依赖数据')),
                ('apicase_execute', models.BooleanField(default=1, verbose_name='是否执行')),
                ('apicase_response', models.CharField(max_length=200, null=True, verbose_name='响应数据')),
                ('apicase_assert', models.CharField(max_length=50, null=True, verbose_name='断言')),
                ('apicase_result', models.BooleanField(default=0, null=True, verbose_name='执行结果')),
                ('apicase_needstore', models.CharField(max_length=100, null=True, verbose_name='需要存储')),
                ('apicase_storedata', models.CharField(max_length=100, null=True, verbose_name='存储数据')),
                ('apicase_taketime', models.CharField(max_length=20, null=True, verbose_name='执行耗时')),
                ('apicase_others', models.CharField(max_length=100, null=True, verbose_name='其他信息')),
                ('execute_time', models.DateTimeField(auto_now=True, verbose_name='执行时间')),
            ],
            options={
                'verbose_name': '接口用例',
                'verbose_name_plural': '接口用例管理',
            },
        ),
        migrations.CreateModel(
            name='ApiInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interface_name', models.CharField(max_length=50, verbose_name='接口名称')),
                ('interface_url', models.CharField(max_length=100, verbose_name='接口地址')),
                ('interface_method', models.CharField(choices=[('get', 'get'), ('post', 'post'), ('put', 'put'), ('patch', 'patch'), ('delete', 'delete')], default='get', max_length=20, verbose_name='请求方法')),
                ('interface_param', models.CharField(max_length=200, null=True, verbose_name='请求参数')),
                ('interface_others', models.CharField(max_length=100, null=True, verbose_name='其他信息')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('module_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.ModuleInfo')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductInfo')),
            ],
            options={
                'verbose_name': '接口信息',
                'verbose_name_plural': '接口信息管理',
            },
        ),
        migrations.AddField(
            model_name='apicaseinfo',
            name='api_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.ApiInfo'),
        ),
        migrations.AddField(
            model_name='apicaseinfo',
            name='module_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.ModuleInfo'),
        ),
        migrations.AddField(
            model_name='apicaseinfo',
            name='product_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductInfo'),
        ),
    ]
