# Generated by Django 2.1.3 on 2019-06-20 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0003_auto_20190620_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='apicaseinfo',
            name='create_time',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='apicaseinfo',
            name='execute_time',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='执行时间'),
        ),
    ]
