# Generated by Django 2.1.3 on 2019-06-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0007_auto_20190622_1612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicaseinfo',
            name='apicase_result',
            field=models.BooleanField(default=0, null=True, verbose_name='执行结果'),
        ),
    ]
