# Generated by Django 2.1.3 on 2019-06-22 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0009_auto_20190622_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicaseinfo',
            name='apicase_response',
            field=models.CharField(default='', max_length=300, null=True, verbose_name='响应数据'),
        ),
    ]
