# Generated by Django 2.1.3 on 2019-06-23 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0003_auto_20190620_1038'),
        ('product', '0001_initial'),
        ('apitest', '0010_auto_20190622_2241'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApisInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='流程名称')),
                ('desc', models.CharField(max_length=100, null=True, verbose_name='描述')),
                ('execute', models.BooleanField(default=1, verbose_name='是否执行')),
                ('caseids', models.CharField(max_length=100, null=True, verbose_name='用例ids')),
                ('others', models.CharField(max_length=100, null=True, verbose_name='其他信息')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('module_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='module.ModuleInfo')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductInfo')),
            ],
            options={
                'verbose_name': '流程接口',
                'verbose_name_plural': '流程接口管理',
            },
        ),
    ]
