# Generated by Django 2.1.3 on 2019-06-20 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('module', '0002_moduleinfo_create_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moduleinfo',
            name='module_name',
            field=models.CharField(max_length=50, unique=True, verbose_name='模块名称'),
        ),
    ]
