# Generated by Django 2.1.3 on 2019-06-18 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_name', models.CharField(max_length=50, verbose_name='模块名称')),
                ('module_desc', models.CharField(max_length=100, null=True, verbose_name='模块描述')),
                ('module_dev', models.CharField(max_length=100, null=True, verbose_name='开发人员')),
                ('module_tst', models.CharField(max_length=30, null=True, verbose_name='测试负责人')),
                ('module_others', models.CharField(max_length=100, null=True, verbose_name='其他信息')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.ProductInfo')),
            ],
            options={
                'verbose_name': '模块信息',
                'verbose_name_plural': '模块管理',
            },
        ),
    ]
