# Generated by Django 2.1.3 on 2019-06-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='createtime',
            field=models.DateTimeField(auto_now=True, verbose_name='创建时间'),
        ),
    ]
