# Generated by Django 2.1.3 on 2019-06-21 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0004_auto_20190620_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicaseinfo',
            name='apicase_relydata',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='依赖数据'),
        ),
        migrations.AlterField(
            model_name='apicaseinfo',
            name='apicase_response',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='响应数据'),
        ),
    ]
