# Generated by Django 2.1.3 on 2019-06-22 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0005_auto_20190621_0857'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apicaseinfo',
            name='apicase_storedata',
        ),
        migrations.AddField(
            model_name='apicaseinfo',
            name='storedata',
            field=models.CharField(default='', max_length=100, null=True, verbose_name='存储数据'),
        ),
        migrations.AlterField(
            model_name='apicaseinfo',
            name='apicase_relydata',
            field=models.CharField(max_length=100, null=True, verbose_name='依赖数据'),
        ),
        migrations.AlterField(
            model_name='apicaseinfo',
            name='apicase_taketime',
            field=models.CharField(default='', max_length=20, null=True, verbose_name='执行耗时'),
        ),
    ]
