# Generated by Django 2.1.3 on 2019-06-22 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0008_auto_20190622_1636'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apicaseinfo',
            name='storedata',
            field=models.CharField(default='', max_length=200, null=True, verbose_name='存储数据'),
        ),
    ]
