# Generated by Django 2.1.3 on 2019-06-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0011_apisinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='apisinfo',
            name='executecases',
            field=models.CharField(max_length=100, null=True, verbose_name='包含的用例'),
        ),
    ]
