# Generated by Django 2.1.3 on 2019-06-24 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apitest', '0013_auto_20190624_0838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='apisinfo',
            old_name='executecases',
            new_name='executecase',
        ),
        migrations.AlterField(
            model_name='apisinfo',
            name='case_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='apitest.ApicaseInfo'),
        ),
        migrations.AlterField(
            model_name='apisinfo',
            name='module_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='module.ModuleInfo'),
        ),
        migrations.AlterField(
            model_name='apisinfo',
            name='product_id',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='product.ProductInfo'),
        ),
    ]
