# Generated by Django 2.1.3 on 2019-06-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50, unique=True, verbose_name='产品名称')),
                ('product_desc', models.CharField(max_length=100, null=True, verbose_name='产品描述')),
                ('product_manager', models.CharField(max_length=20, verbose_name='产品负责人')),
                ('product_others', models.CharField(max_length=200, null=True, verbose_name='其他信息')),
                ('create_time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '产品信息',
                'verbose_name_plural': '产品管理',
            },
        ),
    ]
